# Generated by Django 5.2 on 2025-04-09 11:23

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_initial_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    Admins = apps.get_model('register', 'Admins')

    admin_group, created = Group.objects.get_or_create(name='Admins')
    # customer_group, created = Group.objects.get_or_create(name='Customers')

    if not User.objects.filter(username="admin1").exists():
        admin_user = User.objects.create(
            first_name='Admin',
            last_name='Admin',
            username="admin1",
            password=make_password('admin1'),
            email='admin@gmail.com',
            is_staff=True
        )
        admin_user.groups.add(admin_group)
        Admins.objects.create(user=admin_user)


def reverse_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    try:
        admin = User.objects.get(username="admin1")
        admin.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('register', '0002_create_groups'),
    ]

    operations = [
        migrations.RunPython(create_initial_admin, reverse_func),
    ]


